services:
  master:
    build:
      context: ./master
    container_name: hadoop-master
    hostname: master
    ports:
      - "9870:9870" # HDFS Web UI
      - "8088:8088" # YARN Resource Manager UI
      - "2222:22"
      - "9000:9000"
    volumes:
      - master_data:/hadoop_data
    networks:
      - hadoop-network

  datanode1:
    build:
      context: ./datanode
    container_name: hadoop-datanode1
    hostname: datanode1
    networks:
      - hadoop-network
    volumes:
      - datanode1_data:/hadoop_data

  datanode2:
    build:
      context: ./datanode
    container_name: hadoop-datanode2
    hostname: datanode2
    networks:
      - hadoop-network
    volumes:
      - datanode2_data:/hadoop_data

volumes:
  master_data:
  datanode1_data:
  datanode2_data:

networks:
  hadoop-network:
